// <auto-generated />
using System;
using JobHarmony.Areas.Quiz.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobHarmony.Areas.Quiz.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    [Migration("20260221230355_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("JobHarmony.Areas.Quiz.Models.CareerMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CareerProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MatchScore")
                        .HasColumnType("REAL");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CareerProfileId");

                    b.HasIndex("SessionId");

                    b.ToTable("CareerMatches");
                });

            modelBuilder.Entity("JobHarmony.Areas.Quiz.Models.CareerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Agreeableness")
                        .HasColumnType("REAL");

                    b.Property<double>("Artistic")
                        .HasColumnType("REAL");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Conscientiousness")
                        .HasColumnType("REAL");

                    b.Property<double>("Conventional")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<double>("EmotionalStability")
                        .HasColumnType("REAL");

                    b.Property<double>("Enterprising")
                        .HasColumnType("REAL");

                    b.Property<double>("EnvCollaboration")
                        .HasColumnType("REAL");

                    b.Property<double>("EnvPace")
                        .HasColumnType("REAL");

                    b.Property<double>("EnvStructure")
                        .HasColumnType("REAL");

                    b.Property<double>("Extraversion")
                        .HasColumnType("REAL");

                    b.Property<double>("Investigative")
                        .HasColumnType("REAL");

                    b.Property<double>("Openness")
                        .HasColumnType("REAL");

                    b.Property<double>("Realistic")
                        .HasColumnType("REAL");

                    b.Property<double>("Social")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("ValAutonomy")
                        .HasColumnType("REAL");

                    b.Property<double>("ValChallenge")
                        .HasColumnType("REAL");

                    b.Property<double>("ValSecurity")
                        .HasColumnType("REAL");

                    b.Property<double>("ValService")
                        .HasColumnType("REAL");

                    b.Property<double>("ValWorkLifeBalance")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("CareerProfiles");
                });

            modelBuilder.Entity("JobHarmony.Areas.Quiz.Models.DimensionScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("NormalizedScore")
                        .HasColumnType("REAL");

                    b.Property<double>("RawScore")
                        .HasColumnType("REAL");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subdimension")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("DimensionScores");
                });

            modelBuilder.Entity("JobHarmony.Areas.Quiz.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReverseScored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SectionOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subdimension")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Tier", "Section", "SectionOrder");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("JobHarmony.Areas.Quiz.Models.QuizSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("QuizSessions");
                });

            modelBuilder.Entity("JobHarmony.Areas.Quiz.Models.Response", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnswerValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SessionId", "QuestionId")
                        .IsUnique();

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("JobHarmony.Areas.Quiz.Models.CareerMatch", b =>
                {
                    b.HasOne("JobHarmony.Areas.Quiz.Models.CareerProfile", "CareerProfile")
                        .WithMany("Matches")
                        .HasForeignKey("CareerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobHarmony.Areas.Quiz.Models.QuizSession", "Session")
                        .WithMany("CareerMatches")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerProfile");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("JobHarmony.Areas.Quiz.Models.DimensionScore", b =>
                {
                    b.HasOne("JobHarmony.Areas.Quiz.Models.QuizSession", "Session")
                        .WithMany("DimensionScores")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("JobHarmony.Areas.Quiz.Models.Response", b =>
                {
                    b.HasOne("JobHarmony.Areas.Quiz.Models.Question", "Question")
                        .WithMany("Responses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobHarmony.Areas.Quiz.Models.QuizSession", "Session")
                        .WithMany("Responses")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("JobHarmony.Areas.Quiz.Models.CareerProfile", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("JobHarmony.Areas.Quiz.Models.Question", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("JobHarmony.Areas.Quiz.Models.QuizSession", b =>
                {
                    b.Navigation("CareerMatches");

                    b.Navigation("DimensionScores");

                    b.Navigation("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
